apiVersion: monitoring.googleapis.com/v1beta
kind: RunMonitoring
metadata:
  name: example-service-api-v2   # ชื่อ service คุณ
spec:
  endpoints:
  - port: 9090          # metrics bare server (ไม่ใช่ Nest public PORT)
    path: /metrics
    interval: 30s
  targetLabels:
    metadata:
    - service
    - revision