apiVersion: monitoring.googleapis.com/v1beta
kind: RunMonitoring
metadata:
  name: example-service-api-v2
spec:
  endpoints:
    # scrape metrics server ใน app container (ไม่ใช่ Nest public PORT)
    - port: "9090"
      path: /metrics
      interval: 30s
